app:
     resource: "@AppBundle/Controller/DefaultController.php"
     type:     annotation

api:
    type:     rest
    resource: AppBundle\Controller\ApiController
    prefix:   /api/v1

#"@AppBundle/Controller/ApiController.php"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
