api:
    type:     rest
    resource: AppBundle\Controller\ExpenseController
    prefix:   /api/v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# This will also catch everything else
wildcard_route:
    path: /{stuff}
    requirements:
        stuff: .+
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    "::index.html.twig"

# and finally, the generic home page
# probably already caught by the wildcard, but I like to be explicit.
app:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    "::index.html.twig"
